### PR TITLE
README: add venv instructions

### PR DESCRIPTION
**Pull request by proppy**
/cc @Fleker @devunwired can you test on a Mac? 

Closes #41

### CODE REVIEW

**Comment by Fleker** [comment]
`pip install google-auth-oauthlib[tool] --user`
Ran the first command on Mac. Seemed like the tool downloaded.

Then tried to run the command: `-bash: google-oauthlib-tool: command not found`

**Comment by irataxy** [comment]
I got the same results as @Fleker.

**Comment by proppy** [comment]
@irataxy @Fleker can you check if this got installed in ` ~/Library/Python/2.7/bin` it might be missing in your `$PATH`.

**Comment by irataxy** [comment]
It was installed in that location:

ls -l ~/Library/Python/2.7/bin
total 72
-rwxr-xr-x  1 nickcook  eng  236 Jul 25 08:40 google-oauthlib-tool

**Comment by proppy** [comment]
@irataxy can you check if `PYTHONUSERBASE` is defined.

With
```
echo $PYTHONUSERBASE
```

**Comment by proppy** [comment]
And please also try:
```
python -c 'import site; print(site.USER_BASE);
```

**Comment by irataxy** [comment]
nickcook-macbookair:~ nickcook$ echo $PYTHONUSERBASE

nickcook-macbookair:~ nickcook$ python -c 'import site; print(site.USER_BASE);
> 
> print(site.USER_BASE);
>

**Comment by irataxy** [comment]
python -c 'import site; print(site.USER_BASE); did not print anything out

**Comment by proppy** [comment]
Then maybe it's best to document how to create the virtualenv.

**Comment by proppy** [comment]
@irataxy @Fleker PTAL

**Comment by proppy** [comment]
@Fleker should we merge this?

**Comment by Fleker** [comment]
It will be useful to include these instructions in the README.

**Comment by proppy** [comment]
Taking that as a LGTM :)

**Pull request merged**
